# Для запуска: docker-compose up -d, сайт будет доступен на http://127.0.0.1:8080/
#
version: "3.4"
x-logging: &default-logging
  options:
    max-size: '12m'
    max-file: '5'
  driver: json-file


services:
  clickhouse:
    image: yandex/clickhouse-server
  web:
    image: nginx:alpine
    restart: always
    logging: *default-logging
    ports:
      - "80:80"
    volumes:
      - ./www:/var/www/
      - ./site.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
      - clickhouse
  php:
    build:
      context: ./containers/php-fpm/.
    logging: *default-logging
    environment:
      XDEBUG_CONFIG: 'remote_host=host.docker.internal'
      PHP_IDE_CONFIG: 'serverName=DockerApp'
    volumes:
      - ./www:/var/www/
      - ./xdebug.ini:/usr/local/etc/php-fpm.d/zz-xdebug.conf
